services:
    ADS\Util\MetadataExtractor\AttributeExtractor: ~
    ADS\Util\MetadataExtractor\ClassExtractor: ~
    ADS\Util\MetadataExtractor\MetadataExtractor:
        arguments:
            - '@ADS\Util\MetadataExtractor\AttributeExtractor'
            - '@ADS\Util\MetadataExtractor\ClassExtractor'
